import type {
  ChatFlowConfig,
  ChatFlowMessage,
  ChatFlowState,
  CollectedFieldValue,
} from '../types';
import { ChatFlowStore } from './store';
import { ChatFlowApi } from '../api/client';

let idCounter = 0;
function nextId(): string {
  return `cf_${Date.now()}_${++idCounter}`;
}

/**
 * Core ChatFlow client. Framework-agnostic — use directly or via React hooks.
 *
 * ```ts
 * const client = new ChatFlowClient({ endpoint: '/api/chatflow' });
 * await client.start();
 * await client.send('My name is Yuki');
 * client.subscribe(() => console.log(client.state));
 * ```
 */
export class ChatFlowClient {
  readonly store: ChatFlowStore;
  private readonly api: ChatFlowApi;
  private readonly config: ChatFlowConfig;

  constructor(config: ChatFlowConfig) {
    this.config = config;
    this.store = new ChatFlowStore();
    this.api = new ChatFlowApi(config);
  }

  // ── Getters ────────────────────────────────────────────────────────────

  get state(): Readonly<ChatFlowState> {
    return this.store.getState();
  }

  get messages(): readonly ChatFlowMessage[] {
    return this.store.messages;
  }

  get collectedData(): Readonly<Record<string, unknown>> {
    return this.store.collectedData;
  }

  get isComplete(): boolean {
    return this.store.isComplete;
  }

  // ── Subscriptions ──────────────────────────────────────────────────────

  subscribe(listener: () => void): () => void {
    return this.store.subscribe(listener);
  }

  // ── Session lifecycle ──────────────────────────────────────────────────

  async start(): Promise<void> {
    this.store.dispatch({ type: 'SET_STATUS', payload: 'loading' });

    try {
      const session = await this.api.createSession(this.config.prefilledData);

      this.store.dispatch({ type: 'SET_SESSION', payload: session.sessionId });

      // Use the engine's greeting (generated by sending [START] during session creation).
      // Fall back to the config greeting if the engine didn't return one.
      const greeting = (session as any).greeting || this.config.greeting || '';
      if (greeting) {
        this.store.dispatch({
          type: 'ADD_MESSAGE',
          payload: {
            id: nextId(),
            role: 'assistant',
            content: greeting,
            timestamp: Date.now(),
          },
        });
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Failed to start session';
      this.store.dispatch({
        type: 'SET_ERROR',
        payload: { code: 'SESSION_START_FAILED', message: msg, retryable: true },
      });
      this.config.onError?.({ code: 'SESSION_START_FAILED', message: msg, retryable: true });
    }
  }

  async send(text: string): Promise<void> {
    const trimmed = text.trim();
    if (!trimmed || !this.state.sessionId || this.store.isSending) return;

    this.store.dispatch({ type: 'SET_SENDING', payload: true });
    this.store.dispatch({ type: 'SET_ERROR', payload: null });

    const userMsg: ChatFlowMessage = {
      id: nextId(),
      role: 'user',
      content: trimmed,
      timestamp: Date.now(),
    };
    this.store.dispatch({ type: 'ADD_MESSAGE', payload: userMsg });

    try {
      const result = await this.api.sendInput(this.state.sessionId, trimmed);

      if (result.message) {
        const agentMsg: ChatFlowMessage = {
          id: nextId(),
          role: 'assistant',
          content: result.message,
          timestamp: Date.now(),
          fieldId: result.currentFieldId ?? undefined,
        };
        this.store.dispatch({ type: 'ADD_MESSAGE', payload: agentMsg });
        this.config.onMessage?.(agentMsg);
      }

      // Update collected data from the handler response (already flattened server-side)
      if (result.collectedData && Object.keys(result.collectedData).length > 0) {
        const prev = this.state.collectedData;
        this.store.dispatch({ type: 'SET_COLLECTED_DATA', payload: result.collectedData });

        if (this.config.onFieldExtracted) {
          for (const [key, value] of Object.entries(result.collectedData)) {
            if (prev[key] !== value) {
              this.config.onFieldExtracted(key, value, { ...prev, ...result.collectedData });
            }
          }
        }
      }

      if (result.currentFieldId != null || result.progressPercent != null) {
        this.store.dispatch({
          type: 'SET_PROGRESS',
          payload: {
            fieldId: result.currentFieldId,
            percent: result.progressPercent ?? this.state.progressPercent,
          },
        });
      }

      if (result.sessionComplete) {
        this.store.dispatch({ type: 'SET_STATUS', payload: 'completed' });
        this.config.onComplete?.(this.state.collectedData);
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Failed to send message';
      const retryable = (err as any)?.retryable ?? true;
      this.store.dispatch({
        type: 'SET_ERROR',
        payload: { code: 'SEND_FAILED', message: msg, retryable },
      });
      this.config.onError?.({ code: 'SEND_FAILED', message: msg, retryable });
    } finally {
      this.store.dispatch({ type: 'SET_SENDING', payload: false });
    }
  }

  reset(): void {
    this.store.dispatch({ type: 'RESET' });
  }
}

export function createChatFlowClient(config: ChatFlowConfig): ChatFlowClient {
  return new ChatFlowClient(config);
}
